include("${CMAKE_CURRENT_LIST_DIR}/../../Shared/TargetArchitecture.cmake")

set(CMAKE_SYSTEM_NAME Windows)
octaryn_arch_select(OCTARYN_WINDOWS_CLANG_TRIPLE x86_64-w64-mingw32 aarch64-w64-mingw32)
octaryn_arch_select(OCTARYN_WINDOWS_SYSTEM_PROCESSOR x86_64 aarch64)
set(CMAKE_SYSTEM_PROCESSOR "${OCTARYN_WINDOWS_SYSTEM_PROCESSOR}")

set(OCTARYN_WINDOWS_CLANG_ROOT "$ENV{OCTARYN_WINDOWS_CLANG_ROOT}" CACHE PATH "Windows Clang toolchain root")
if(NOT OCTARYN_WINDOWS_CLANG_ROOT AND EXISTS "/opt/llvm-mingw")
    set(OCTARYN_WINDOWS_CLANG_ROOT "/opt/llvm-mingw" CACHE PATH "Windows Clang toolchain root" FORCE)
endif()

find_program(OCTARYN_WINDOWS_CLANG_C_COMPILER ${OCTARYN_WINDOWS_CLANG_TRIPLE}-clang
    PATHS "${OCTARYN_WINDOWS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_WINDOWS_CLANG_CXX_COMPILER ${OCTARYN_WINDOWS_CLANG_TRIPLE}-clang++
    PATHS "${OCTARYN_WINDOWS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_WINDOWS_CLANG_RC_COMPILER ${OCTARYN_WINDOWS_CLANG_TRIPLE}-windres
    PATHS "${OCTARYN_WINDOWS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_WINDOWS_CLANG_AR ${OCTARYN_WINDOWS_CLANG_TRIPLE}-ar
    PATHS "${OCTARYN_WINDOWS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_WINDOWS_CLANG_RANLIB ${OCTARYN_WINDOWS_CLANG_TRIPLE}-ranlib
    PATHS "${OCTARYN_WINDOWS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)

if(NOT OCTARYN_WINDOWS_CLANG_C_COMPILER OR NOT OCTARYN_WINDOWS_CLANG_CXX_COMPILER OR NOT OCTARYN_WINDOWS_CLANG_RC_COMPILER OR NOT OCTARYN_WINDOWS_CLANG_AR OR NOT OCTARYN_WINDOWS_CLANG_RANLIB)
    message(FATAL_ERROR "Windows ${OCTARYN_TARGET_ARCH} cross-build requires ${OCTARYN_WINDOWS_CLANG_TRIPLE} LLVM MinGW tools under OCTARYN_WINDOWS_CLANG_ROOT.")
endif()

set(CMAKE_C_COMPILER "${OCTARYN_WINDOWS_CLANG_C_COMPILER}" CACHE FILEPATH "Windows Clang C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${OCTARYN_WINDOWS_CLANG_CXX_COMPILER}" CACHE FILEPATH "Windows Clang C++ compiler" FORCE)
set(CMAKE_RC_COMPILER "${OCTARYN_WINDOWS_CLANG_RC_COMPILER}" CACHE FILEPATH "Windows Clang resource compiler" FORCE)
set(CMAKE_AR "${OCTARYN_WINDOWS_CLANG_AR}" CACHE FILEPATH "Windows Clang archiver" FORCE)
set(CMAKE_RANLIB "${OCTARYN_WINDOWS_CLANG_RANLIB}" CACHE FILEPATH "Windows Clang ranlib" FORCE)
set(CMAKE_C_COMPILER_AR "${OCTARYN_WINDOWS_CLANG_AR}" CACHE FILEPATH "Windows Clang C compiler archiver" FORCE)
set(CMAKE_CXX_COMPILER_AR "${OCTARYN_WINDOWS_CLANG_AR}" CACHE FILEPATH "Windows Clang C++ compiler archiver" FORCE)
set(CMAKE_C_COMPILER_RANLIB "${OCTARYN_WINDOWS_CLANG_RANLIB}" CACHE FILEPATH "Windows Clang C compiler ranlib" FORCE)
set(CMAKE_CXX_COMPILER_RANLIB "${OCTARYN_WINDOWS_CLANG_RANLIB}" CACHE FILEPATH "Windows Clang C++ compiler ranlib" FORCE)
set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>" CACHE STRING "Windows C static archive rule" FORCE)
set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>" CACHE STRING "Windows C++ static archive rule" FORCE)
set(CMAKE_ASM_ARCHIVE_CREATE "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>" CACHE STRING "Windows ASM static archive rule" FORCE)
set(CMAKE_C_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>" CACHE STRING "Windows C static archive finish rule" FORCE)
set(CMAKE_CXX_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>" CACHE STRING "Windows C++ static archive finish rule" FORCE)
set(CMAKE_ASM_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>" CACHE STRING "Windows ASM static archive finish rule" FORCE)

set(CMAKE_FIND_ROOT_PATH
    "${OCTARYN_WINDOWS_CLANG_ROOT}"
    "${OCTARYN_WINDOWS_CLANG_ROOT}/${OCTARYN_WINDOWS_CLANG_TRIPLE}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
