set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(OCTARYN_WINDOWS_CLANG_ROOT "$ENV{OCTARYN_WINDOWS_CLANG_ROOT}" CACHE PATH "Windows Clang toolchain root")
if(NOT OCTARYN_WINDOWS_CLANG_ROOT AND EXISTS "/opt/llvm-mingw")
    set(OCTARYN_WINDOWS_CLANG_ROOT "/opt/llvm-mingw" CACHE PATH "Windows Clang toolchain root" FORCE)
endif()

find_program(OCTARYN_WINDOWS_CLANG_C_COMPILER x86_64-w64-mingw32-clang
    PATHS "${OCTARYN_WINDOWS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_WINDOWS_CLANG_CXX_COMPILER x86_64-w64-mingw32-clang++
    PATHS "${OCTARYN_WINDOWS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_WINDOWS_CLANG_RC_COMPILER x86_64-w64-mingw32-windres
    PATHS "${OCTARYN_WINDOWS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_WINDOWS_CLANG_AR x86_64-w64-mingw32-ar
    PATHS "${OCTARYN_WINDOWS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_WINDOWS_CLANG_RANLIB x86_64-w64-mingw32-ranlib
    PATHS "${OCTARYN_WINDOWS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)

set(CMAKE_C_COMPILER "${OCTARYN_WINDOWS_CLANG_C_COMPILER}" CACHE FILEPATH "Windows Clang C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${OCTARYN_WINDOWS_CLANG_CXX_COMPILER}" CACHE FILEPATH "Windows Clang C++ compiler" FORCE)
set(CMAKE_RC_COMPILER "${OCTARYN_WINDOWS_CLANG_RC_COMPILER}" CACHE FILEPATH "Windows Clang resource compiler" FORCE)
set(CMAKE_AR "${OCTARYN_WINDOWS_CLANG_AR}" CACHE FILEPATH "Windows Clang archiver" FORCE)
set(CMAKE_RANLIB "${OCTARYN_WINDOWS_CLANG_RANLIB}" CACHE FILEPATH "Windows Clang ranlib" FORCE)

set(CMAKE_FIND_ROOT_PATH
    "${OCTARYN_WINDOWS_CLANG_ROOT}"
    "${OCTARYN_WINDOWS_CLANG_ROOT}/x86_64-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
