include_guard(GLOBAL)

set(OCTARYN_CLIENT_DEPENDENCIES_SCAFFOLD ON)

add_library(octaryn_client_sdl3 INTERFACE)
add_library(octaryn::deps::sdl3 ALIAS octaryn_client_sdl3)

find_package(SDL3 CONFIG QUIET)
if(TARGET SDL3::SDL3)
    target_link_libraries(octaryn_client_sdl3 INTERFACE SDL3::SDL3)
endif()

if(NOT TARGET octaryn::deps::openal)
    add_library(octaryn_client_openal INTERFACE)
    add_library(octaryn::deps::openal ALIAS octaryn_client_openal)

    find_package(OpenAL CONFIG QUIET)
    if(TARGET OpenAL::OpenAL)
        target_link_libraries(octaryn_client_openal INTERFACE OpenAL::OpenAL)
    elseif(TARGET OpenAL)
        target_link_libraries(octaryn_client_openal INTERFACE OpenAL)
    else()
        find_package(OpenAL QUIET)
        if(TARGET OpenAL::OpenAL)
            target_link_libraries(octaryn_client_openal INTERFACE OpenAL::OpenAL)
        elseif(OpenAL_FOUND)
            target_include_directories(octaryn_client_openal SYSTEM INTERFACE "${OPENAL_INCLUDE_DIR}")
            target_link_libraries(octaryn_client_openal INTERFACE "${OPENAL_LIBRARY}")
        endif()
    endif()
endif()

if(NOT TARGET octaryn::deps::miniaudio)
    add_library(octaryn_client_miniaudio INTERFACE)
    add_library(octaryn::deps::miniaudio ALIAS octaryn_client_miniaudio)

    find_package(miniaudio CONFIG QUIET)
    if(TARGET miniaudio::miniaudio)
        target_link_libraries(octaryn_client_miniaudio INTERFACE miniaudio::miniaudio)
    elseif(TARGET miniaudio)
        target_link_libraries(octaryn_client_miniaudio INTERFACE miniaudio)
    else()
        find_path(OCTARYN_MINIAUDIO_INCLUDE_DIR miniaudio.h)
        if(OCTARYN_MINIAUDIO_INCLUDE_DIR)
            target_include_directories(octaryn_client_miniaudio SYSTEM INTERFACE "${OCTARYN_MINIAUDIO_INCLUDE_DIR}")
        endif()
    endif()
endif()

if(NOT TARGET octaryn::deps::glaze)
    add_library(octaryn_client_glaze INTERFACE)
    add_library(octaryn::deps::glaze ALIAS octaryn_client_glaze)

    find_package(glaze CONFIG QUIET)
    if(TARGET glaze::glaze)
        target_link_libraries(octaryn_client_glaze INTERFACE glaze::glaze)
    endif()
endif()
