include_guard(GLOBAL)
if(CMAKE_CROSSCOMPILING OR NOT CMAKE_SYSTEM_NAME MATCHES "^(Linux|Darwin)$")
    message(FATAL_ERROR "Build standalone slang-rhi natively on Windows, Linux, or macOS; cross compilation is not qualified.")
endif()
if(APPLE)
    set(rhi_platform macos)
    set(rhi_backend Metal)
    set(rhi_library_suffix dylib)
else()
    set(rhi_platform linux)
    set(rhi_backend Vulkan)
    set(rhi_library_suffix so)
endif()
set(rhi_configuration Release)
if(CMAKE_BUILD_TYPE)
    set(rhi_configuration "${CMAKE_BUILD_TYPE}")
endif()
set(OCTARYN_SLANG_RHI_COMMIT e17f6d75f858f9b7cb91bc102a7b8c6fda0435dc)
set(OCTARYN_SLANG_SDK_ROOT "$ENV{SLANG_SDK_ROOT}" CACHE PATH "Slang compiler SDK root")
if(NOT OCTARYN_SLANG_SDK_ROOT)
    set(OCTARYN_SLANG_SDK_ROOT "${OCTARYN_WORKSPACE_ROOT_DIR}/build/dependencies/slang-2026.17.1-${rhi_platform}-${OCTARYN_TARGET_ARCH}" CACHE PATH "Slang compiler SDK root" FORCE)
endif()
set(OCTARYN_SLANG_RHI_SOURCE_ROOT "${OCTARYN_WORKSPACE_ROOT_DIR}/build/dependencies/slang-rhi" CACHE PATH "Pinned standalone slang-rhi checkout")
set(OCTARYN_SLANG_RHI_BUILD_ROOT "${OCTARYN_WORKSPACE_ROOT_DIR}/build/dependencies/slang-rhi-${rhi_platform}-${OCTARYN_TARGET_ARCH}-${rhi_configuration}" CACHE PATH "Native standalone static slang-rhi build")
unset(OCTARYN_SLANG_RHI_LIBRARY CACHE)
unset(OCTARYN_SLANG_RHI_INCLUDE_DIR CACHE)
unset(OCTARYN_SLANGC_EXECUTABLE CACHE)
set(OCTARYN_SLANG_RHI_INCLUDE_DIR "${OCTARYN_SLANG_RHI_SOURCE_ROOT}/include")
find_program(OCTARYN_SLANGC_EXECUTABLE NAMES slangc PATHS "${OCTARYN_SLANG_SDK_ROOT}/bin" NO_DEFAULT_PATH)
set(rhi_libraries "${OCTARYN_SLANG_RHI_BUILD_ROOT}/libslang-rhi-resources.a")
if(NOT APPLE)
    list(PREPEND rhi_libraries "${OCTARYN_SLANG_RHI_BUILD_ROOT}/libslang-rhi-vma.a")
endif()
set(rhi_compiler "${OCTARYN_SLANG_SDK_ROOT}/lib/libslang-compiler.${rhi_library_suffix}")
foreach(required IN ITEMS
    "${OCTARYN_SLANG_RHI_INCLUDE_DIR}/slang-rhi.h"
    "${OCTARYN_SLANG_RHI_BUILD_ROOT}/include/slang-rhi-config.h"
    "${OCTARYN_SLANG_RHI_BUILD_ROOT}/octaryn-dependency.cmake"
    "${OCTARYN_SLANG_RHI_BUILD_ROOT}/libslang-rhi.a"
    "${OCTARYN_SLANG_SDK_ROOT}/include/slang.h"
    "${OCTARYN_SLANGC_EXECUTABLE}" "${rhi_compiler}" ${rhi_libraries})
    if(NOT EXISTS "${required}")
        message(FATAL_ERROR "Standalone slang-rhi prerequisite missing: ${required}. Run python3 tools/build/slang-rhi.py --configuration ${rhi_configuration} natively, then configure again.")
    endif()
endforeach()
include("${OCTARYN_SLANG_RHI_BUILD_ROOT}/octaryn-dependency.cmake")
file(REAL_PATH "${OCTARYN_SLANG_SDK_ROOT}" sdk_root)
file(REAL_PATH "${OCTARYN_SLANG_RHI_BUILT_SDK_ROOT}" built_sdk_root)
if(NOT OCTARYN_SLANG_RHI_BUILT_COMMIT STREQUAL OCTARYN_SLANG_RHI_COMMIT OR
   NOT sdk_root STREQUAL built_sdk_root OR
   NOT OCTARYN_SLANG_RHI_BUILT_PLATFORM STREQUAL rhi_platform OR
   NOT OCTARYN_SLANG_RHI_BUILT_ARCH STREQUAL OCTARYN_TARGET_ARCH OR
   NOT OCTARYN_SLANG_RHI_BUILT_CONFIG STREQUAL rhi_configuration OR
   NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "Standalone slang-rhi source/SDK/platform/architecture/configuration mismatch; rebuild the selected native dependency.")
endif()
file(READ "${OCTARYN_SLANG_RHI_BUILD_ROOT}/include/slang-rhi-config.h" rhi_config)
string(TOUPPER "${rhi_backend}" rhi_backend_upper)
if(NOT rhi_config MATCHES "#define SLANG_RHI_ENABLE_${rhi_backend_upper} 1")
    message(FATAL_ERROR "The selected standalone slang-rhi build does not enable ${rhi_backend}.")
endif()
find_package(Threads REQUIRED)
list(APPEND rhi_libraries "${rhi_compiler}" Threads::Threads ${CMAKE_DL_LIBS})
if(APPLE)
    list(APPEND rhi_libraries "-framework Metal" "-framework Foundation" "-framework QuartzCore")
endif()
octaryn_add_dependency_wrapper(octaryn_client_slang_rhi octaryn::deps::slang_rhi)
add_library(octaryn_slang_rhi_native STATIC IMPORTED GLOBAL)
set_target_properties(octaryn_slang_rhi_native PROPERTIES
    IMPORTED_LOCATION "${OCTARYN_SLANG_RHI_BUILD_ROOT}/libslang-rhi.a"
    INTERFACE_LINK_LIBRARIES "${rhi_libraries}")
target_include_directories(octaryn_client_slang_rhi SYSTEM INTERFACE
    "${OCTARYN_SLANG_RHI_INCLUDE_DIR}" "${OCTARYN_SLANG_RHI_BUILD_ROOT}/include" "${OCTARYN_SLANG_SDK_ROOT}/include")
target_compile_definitions(octaryn_client_slang_rhi INTERFACE SLANG_USER_CONFIG="slang-user-config.h")
target_link_libraries(octaryn_client_slang_rhi INTERFACE octaryn_slang_rhi_native)
if(APPLE)
    target_link_options(octaryn_client_slang_rhi INTERFACE "LINKER:-rpath,@loader_path")
else()
    target_link_options(octaryn_client_slang_rhi INTERFACE "LINKER:-rpath,$ORIGIN")
endif()
# Include SONAME aliases as well as real files; copy_if_different dereferences aliases.
file(GLOB OCTARYN_CLIENT_SLANG_RUNTIME_FILES CONFIGURE_DEPENDS
    "${OCTARYN_SLANG_SDK_ROOT}/lib/libslang*.${rhi_library_suffix}*")
foreach(component slang-compiler slang-rt slang-glslang)
    if(NOT EXISTS "${OCTARYN_SLANG_SDK_ROOT}/lib/lib${component}.${rhi_library_suffix}")
        message(FATAL_ERROR "Slang compiler runtime is incomplete: ${component}")
    endif()
endforeach()
set(OCTARYN_CLIENT_SLANG_RHI_AVAILABLE ON)
message(STATUS "Client dependency: standalone slang-rhi ${OCTARYN_SLANG_RHI_COMMIT}, static ${rhi_backend}; native ${rhi_platform} runtime qualification still required")
