set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(OCTARYN_MACOS_CLANG_ROOT "$ENV{OCTARYN_MACOS_CLANG_ROOT}" CACHE PATH "macOS Clang toolchain root")
if(NOT OCTARYN_MACOS_CLANG_ROOT AND EXISTS "/home/zacharyr/toolchains/osxcross/target")
    set(OCTARYN_MACOS_CLANG_ROOT "/home/zacharyr/toolchains/osxcross/target" CACHE PATH "macOS Clang toolchain root" FORCE)
endif()

set(OCTARYN_MACOS_CLANG_SDK_ROOT "$ENV{OCTARYN_MACOS_CLANG_SDK_ROOT}" CACHE PATH "macOS Clang SDK root")
if(NOT OCTARYN_MACOS_CLANG_SDK_ROOT AND EXISTS "${OCTARYN_MACOS_CLANG_ROOT}/SDK/MacOSX15.5.sdk")
    set(OCTARYN_MACOS_CLANG_SDK_ROOT "${OCTARYN_MACOS_CLANG_ROOT}/SDK/MacOSX15.5.sdk" CACHE PATH "macOS Clang SDK root" FORCE)
elseif(NOT OCTARYN_MACOS_CLANG_SDK_ROOT AND EXISTS "/home/zacharyr/toolchains/apple/macos-sdk/MacOSX15.5.sdk")
    set(OCTARYN_MACOS_CLANG_SDK_ROOT "/home/zacharyr/toolchains/apple/macos-sdk/MacOSX15.5.sdk" CACHE PATH "macOS Clang SDK root" FORCE)
endif()

find_program(OCTARYN_MACOS_CLANG_C_COMPILER o64-clang
    PATHS "${OCTARYN_MACOS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_MACOS_CLANG_CXX_COMPILER o64-clang++
    PATHS "${OCTARYN_MACOS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_MACOS_CLANG_OBJC_COMPILER o64-clang
    PATHS "${OCTARYN_MACOS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_MACOS_CLANG_OBJCXX_COMPILER o64-clang++
    PATHS "${OCTARYN_MACOS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_MACOS_CLANG_AR
    NAMES x86_64-apple-darwin24.5-ar x86_64-apple-darwin24-ar
    PATHS "${OCTARYN_MACOS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)
find_program(OCTARYN_MACOS_CLANG_RANLIB
    NAMES x86_64-apple-darwin24.5-ranlib x86_64-apple-darwin24-ranlib
    PATHS "${OCTARYN_MACOS_CLANG_ROOT}/bin"
    NO_DEFAULT_PATH)

set(CMAKE_C_COMPILER "${OCTARYN_MACOS_CLANG_C_COMPILER}" CACHE FILEPATH "macOS Clang C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${OCTARYN_MACOS_CLANG_CXX_COMPILER}" CACHE FILEPATH "macOS Clang C++ compiler" FORCE)
set(CMAKE_OBJC_COMPILER "${OCTARYN_MACOS_CLANG_OBJC_COMPILER}" CACHE FILEPATH "macOS Clang Objective-C compiler" FORCE)
set(CMAKE_OBJCXX_COMPILER "${OCTARYN_MACOS_CLANG_OBJCXX_COMPILER}" CACHE FILEPATH "macOS Clang Objective-C++ compiler" FORCE)
set(CMAKE_AR "${OCTARYN_MACOS_CLANG_AR}" CACHE FILEPATH "macOS Clang archiver" FORCE)
set(CMAKE_RANLIB "${OCTARYN_MACOS_CLANG_RANLIB}" CACHE FILEPATH "macOS Clang ranlib" FORCE)
set(CMAKE_OSX_SYSROOT "${OCTARYN_MACOS_CLANG_SDK_ROOT}" CACHE PATH "macOS Clang SDK" FORCE)
set(CMAKE_OSX_ARCHITECTURES "x86_64" CACHE STRING "macOS Clang target architectures" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET "13.0" CACHE STRING "Minimum macOS deployment target" FORCE)

set(CMAKE_FIND_ROOT_PATH "${OCTARYN_MACOS_CLANG_ROOT}" "${OCTARYN_MACOS_CLANG_SDK_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
