include_guard(GLOBAL)

if(NOT DEFINED OCTARYN_BUILD_PRESET_NAME)
    set(OCTARYN_BUILD_PRESET_NAME "local")
endif()

set(OCTARYN_BUILD_ROOT "${OCTARYN_WORKSPACE_ROOT_DIR}/build")
set(OCTARYN_LOG_ROOT "${OCTARYN_WORKSPACE_ROOT_DIR}/logs")
set(OCTARYN_DEPENDENCY_BUILD_ROOT "${OCTARYN_BUILD_ROOT}/dependencies")
set(OCTARYN_BUILD_LOG_ROOT "${OCTARYN_LOG_ROOT}/build")
