include_guard(GLOBAL)

if(NOT DEFINED OCTARYN_BUILD_PRESET_NAME)
    set(OCTARYN_BUILD_PRESET_NAME "debug-linux")
endif()

set(OCTARYN_BUILD_ROOT "${OCTARYN_WORKSPACE_ROOT_DIR}/build")
set(OCTARYN_LOG_ROOT "${OCTARYN_WORKSPACE_ROOT_DIR}/logs")
set(OCTARYN_BUILD_PRESET_ROOT "${OCTARYN_BUILD_ROOT}/${OCTARYN_BUILD_PRESET_NAME}")
set(OCTARYN_DEPENDENCY_ROOT "${OCTARYN_BUILD_ROOT}/dependencies")
set(OCTARYN_DEPENDENCY_SOURCE_ROOT "${OCTARYN_DEPENDENCY_ROOT}/src")
set(OCTARYN_DEPENDENCY_DOWNLOAD_ROOT "${OCTARYN_DEPENDENCY_ROOT}/downloads")
set(OCTARYN_DEPENDENCY_BUILD_ROOT "${OCTARYN_BUILD_PRESET_ROOT}/deps")
set(OCTARYN_BUILD_LOG_ROOT "${OCTARYN_LOG_ROOT}/build")
