include_guard(GLOBAL)

set(OCTARYN_HOST_PLATFORM "Linux")
set(OCTARYN_LINUX_FAMILY "Unknown" CACHE STRING "Linux distro family for package/tool policy")
find_program(OCTARYN_MINGW_C_COMPILER x86_64-w64-mingw32-gcc)
find_program(OCTARYN_MINGW_CXX_COMPILER x86_64-w64-mingw32-g++)
set(OCTARYN_HOST_SUPPORTS_MINIGW_CROSS OFF)
if(OCTARYN_MINGW_C_COMPILER AND OCTARYN_MINGW_CXX_COMPILER)
    set(OCTARYN_HOST_SUPPORTS_MINIGW_CROSS ON)
endif()

if(OCTARYN_LINUX_FAMILY STREQUAL "Unknown" AND EXISTS "/etc/os-release")
    file(READ "/etc/os-release" octaryn_os_release)
    if(octaryn_os_release MATCHES "(ID|ID_LIKE)=.*(arch|cachyos)")
        set(OCTARYN_LINUX_FAMILY "Arch")
    elseif(octaryn_os_release MATCHES "(ID|ID_LIKE)=.*(debian|ubuntu)")
        set(OCTARYN_LINUX_FAMILY "Debian")
    elseif(octaryn_os_release MATCHES "(ID|ID_LIKE)=.*(fedora|rhel)")
        set(OCTARYN_LINUX_FAMILY "Fedora")
    elseif(octaryn_os_release MATCHES "(ID|ID_LIKE)=.*(suse|opensuse)")
        set(OCTARYN_LINUX_FAMILY "Suse")
    endif()
endif()

if(OCTARYN_LINUX_FAMILY STREQUAL "Arch")
    include(Platforms/Linux/ArchFamily)
elseif(OCTARYN_LINUX_FAMILY STREQUAL "Debian")
    include(Platforms/Linux/DebianFamily)
elseif(OCTARYN_LINUX_FAMILY STREQUAL "Fedora")
    include(Platforms/Linux/FedoraFamily)
elseif(OCTARYN_LINUX_FAMILY STREQUAL "Suse")
    include(Platforms/Linux/SuseFamily)
else()
    set(OCTARYN_TARGET_DOTNET_RID "linux-x64")
    message(STATUS "Octaryn Linux distro family is not classified; distro-specific package hints are disabled.")
endif()
