octaryn_add_native_executable(
    octaryn_shader_compiler
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ShaderCompiler/ShaderCompilerFileInput.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ShaderCompiler/ShaderCompilerMain.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ShaderCompiler"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Diagnostics/NativeCrashDiagnostics"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Diagnostics/NativeLogging"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Memory/NativeMemory"
    PRIVATE_LINKS
        octaryn_native_logging
        octaryn_native_diagnostics
        octaryn_native_memory
        octaryn::deps::glaze
        octaryn::deps::sdl3
        octaryn::deps::shadercross
        octaryn::deps::shaderc
        octaryn::deps::spirv_tools
        octaryn::deps::spirv_cross)

octaryn_add_native_executable(
    octaryn_native_jobs_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/NativeJobsProbe/NativeJobsProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Libraries/NativeJobs"
    PRIVATE_LINKS
        octaryn_native_jobs
        octaryn::deps::taskflow)

octaryn_add_native_executable(
    octaryn_client_chunk_mesh_plan_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ClientChunkMeshPlanProbe/ClientChunkMeshPlanProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/Planning"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/WorldPresentation/ChunkView"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Libraries/NativeJobs"
    PRIVATE_LINKS
        octaryn_client_chunk_mesh_plan
        octaryn_native_jobs
        octaryn::deps::taskflow)

octaryn_add_native_executable(
    octaryn_server_world_time_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldTimeProbe/ServerWorldTimeProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/World/Time"
    PRIVATE_LINKS
        octaryn_server_world_time)
