octaryn_add_native_executable(
    octaryn_shader_compiler
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ShaderCompiler/ShaderCompilerFileInput.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ShaderCompiler/ShaderCompilerMain.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ShaderCompiler"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Diagnostics/NativeCrashDiagnostics"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Diagnostics/NativeLogging"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Memory/NativeMemory"
    PRIVATE_LINKS
        octaryn_native_logging
        octaryn_native_diagnostics
        octaryn_native_memory
        octaryn::deps::glaze
        octaryn::deps::sdl3
        octaryn::deps::shadercross
        octaryn::deps::shaderc
        octaryn::deps::spirv_tools
        octaryn::deps::spirv_cross)

octaryn_add_native_executable(
    octaryn_native_jobs_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/NativeJobsProbe/NativeJobsProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Libraries/NativeJobs"
    PRIVATE_LINKS
        octaryn_native_jobs
        octaryn::deps::taskflow)

octaryn_add_native_executable(
    octaryn_client_chunk_mesh_plan_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ClientChunkMeshPlanProbe/ClientChunkMeshPlanProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/Planning"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/WorldPresentation/ChunkView"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Libraries/NativeJobs"
    PRIVATE_LINKS
        octaryn_client_chunk_mesh_plan
        octaryn_native_jobs
        octaryn::deps::taskflow)

octaryn_add_native_executable(
    octaryn_client_empty_world_mesh_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ClientEmptyWorldMeshProbe/ClientEmptyWorldMeshProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/Geometry/Blocks.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/Geometry/TerrainMeshBatch.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/Geometry/TerrainMesh.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/Packing/Packing.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/Planning/ChunkMeshPlan.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/View/View.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/App/Logging"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/App/PresentationState"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/App/RuntimeFiles"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/HostBridge/Abi"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/Geometry"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/Packing"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/Planning"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/EmptyWorldMesh/View"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/Rendering/WorldMeshUpload"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-client/Source/WorldPresentation/ChunkView"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/HostAbi"
    PRIVATE_LINKS
        octaryn::deps::sdl3)

octaryn_add_native_executable(
    octaryn_server_host_policy_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerHostPolicyProbe/ServerHostPolicyProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/Host"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/HostAbi"
    PRIVATE_LINKS
        octaryn_server_host)

octaryn_add_native_executable(
    octaryn_server_world_time_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldTimeProbe/ServerWorldTimeProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/World/Time"
    PRIVATE_LINKS
        octaryn_server_world_time)

octaryn_add_native_executable(
    octaryn_server_authority_tick_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerAuthorityTickProbe/ServerAuthorityTickProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/Tick"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-shared/Source/Libraries/NativeJobs"
    PRIVATE_LINKS
        octaryn_server_authority_tick
        octaryn_native_jobs)

octaryn_add_native_executable(
    octaryn_server_block_store_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerBlockStoreProbe/ServerBlockStoreProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerBlockStoreProbe/ServerBlockStoreCommandQueueProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerBlockStoreProbe/ServerBlockStoreCommandValidationProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerBlockStoreProbe/ServerBlockStoreChunkRequestProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerBlockStoreProbe/ServerBlockStoreChunkStreamProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/World/Blocks/Store"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/World/Chunks/Streaming"
    PRIVATE_LINKS
        octaryn_server_block_store)

octaryn_add_native_executable(
    octaryn_server_player_simulation_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerPlayerSimulationProbe/ServerPlayerSimulationProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerPlayerSimulationProbe/ServerPlayerSimulationInputIntentProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerPlayerSimulationProbe/ServerPlayerSimulationSaveProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerPlayerSimulationProbe/ServerPlayerSimulationStepProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/Simulation/Players"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/World/Blocks/Store"
    PRIVATE_LINKS
        octaryn_server_player_simulation
        octaryn_server_block_store)

octaryn_add_native_executable(
    octaryn_server_terrain_generation_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerTerrainGenerationProbe/ServerTerrainGenerationProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/World/Blocks/Store"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/World/Generation"
    PRIVATE_LINKS
        octaryn_server_terrain_generation
        octaryn_server_block_store)

octaryn_add_native_executable(
    octaryn_server_world_persistence_probe
    tools
    SOURCES
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldPersistenceProbe/ChunkOverrideDirectoryProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldPersistenceProbe/GzipPersistenceProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldPersistenceProbe/PlayerDirectoryProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldPersistenceProbe/ServerWorldPersistenceProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldPersistenceProbe/WorldBlockExportColumnPlanProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldPersistenceProbe/WorldBlockPersistencePolicyProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldPersistenceProbe/WorldMetadataBuildProbe.cpp"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldPersistenceProbe/WorldSaveImportProbe.cpp"
    PUBLIC_INCLUDE_DIRS
        "${OCTARYN_WORKSPACE_ROOT_DIR}/tools/Source/ServerWorldPersistenceProbe"
        "${OCTARYN_WORKSPACE_ROOT_DIR}/octaryn-server/Source/Persistence/WorldBlocks"
    PRIVATE_LINKS
        octaryn_server_world_persistence)
