add_dependencies(octaryn_tools
    octaryn_native_jobs_probe
    octaryn_client_render_backend_probe
    octaryn_client_voxel_invariants_probe
    octaryn_client_voxel_mesh_probe
    octaryn_client_voxel_indirect_probe
    octaryn_server_host_policy_probe
    octaryn_server_world_time_probe
    octaryn_server_authority_tick_probe
    octaryn_server_block_store_probe
    octaryn_server_player_simulation_probe
    octaryn_server_terrain_generation_probe
    octaryn_server_world_persistence_probe
    octaryn_debug_tools)
