add_dependencies(octaryn_tools
    octaryn_shader_compiler
    octaryn_native_jobs_probe
    octaryn_client_chunk_mesh_plan_probe
    octaryn_client_empty_world_mesh_probe
    octaryn_server_world_time_probe
    octaryn_server_block_store_probe
    octaryn_server_player_simulation_probe
    octaryn_server_terrain_generation_probe
    octaryn_server_world_persistence_probe
    octaryn_debug_tools)
