include_guard(GLOBAL)

include(CheckIPOSupported)

option(OCTARYN_ENABLE_RENDERING "Enable the SDL3 GPU renderer module" ON)
option(OCTARYN_ENABLE_SDL_GPU "Enable the SDL3 GPU renderer backend" ON)
option(OCTARYN_ENABLE_UI_TEXT "Enable SDL3_ttf-backed overlay and menu text rendering" ON)
option(OCTARYN_ENABLE_ASSET_PIPELINE "Enable asset import and compression dependencies" ON)
option(OCTARYN_ENABLE_RUNTIME_ASSET_GENERATION "Generate runtime texture and shader assets during the build" ON)
option(OCTARYN_ENABLE_ANIMATION "Enable skeletal animation dependencies" ON)
option(OCTARYN_ENABLE_PHYSICS "Enable physics dependencies" ON)
option(OCTARYN_ENABLE_AUDIO "Enable audio dependencies" ON)
option(OCTARYN_ENABLE_PROFILING "Enable profiling dependencies" OFF)
option(OCTARYN_ENABLE_TRACY "Enable Tracy profiler instrumentation" OFF)
option(OCTARYN_ENABLE_CRASH_DIAGNOSTICS "Enable crash diagnostics dependencies" OFF)
option(OCTARYN_ENABLE_MANAGED_DOTNET "Enable the embedded .NET managed game host" ON)
option(OCTARYN_ENABLE_LTO "Enable link time optimization in non-Debug builds" OFF)
option(OCTARYN_PREFER_SHARED_DEPS "Prefer shared third-party dependencies when available" OFF)

function(octaryn_setup_project_options)
  set(CMAKE_C_STANDARD 17 PARENT_SCOPE)
  set(CMAKE_C_STANDARD_REQUIRED ON PARENT_SCOPE)
  set(CMAKE_CXX_STANDARD 23 PARENT_SCOPE)
  set(CMAKE_CXX_STANDARD_REQUIRED ON PARENT_SCOPE)
  set(CMAKE_CXX_EXTENSIONS OFF PARENT_SCOPE)

  find_program(OCTARYN_SCCACHE_PROGRAM sccache)
  if(OCTARYN_SCCACHE_PROGRAM)
    set(CMAKE_C_COMPILER_LAUNCHER "${OCTARYN_SCCACHE_PROGRAM}" PARENT_SCOPE)
    set(CMAKE_CXX_COMPILER_LAUNCHER "${OCTARYN_SCCACHE_PROGRAM}" PARENT_SCOPE)
  endif()

  if(OCTARYN_ENABLE_LTO AND NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
    check_ipo_supported(RESULT octaryn_ipo_supported OUTPUT octaryn_ipo_output)
    if(octaryn_ipo_supported)
      set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON PARENT_SCOPE)
    else()
      message(WARNING "IPO/LTO requested but unavailable: ${octaryn_ipo_output}")
    endif()
  endif()
endfunction()

function(octaryn_enable_default_warnings target_name)
  if(MSVC)
    target_compile_options(${target_name} PRIVATE /W4 /permissive-)
  else()
    target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
  endif()
endfunction()
